name = "rsvp"
version = "1.0.0"

description = "Send HTTP requests from Lustre applications and server components."
repository = { type = "github", user = "hayleigh-dot-dev", repo = "rsvp" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
gleam_erlang = ">= 0.30.0 and < 1.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.6.3 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
